;PRINTING MSG
.MODEL SMALL
.STACK 100H

.DATA
MSG DB 'HELLO WORLD$'  
MSG2 DB 0DH,0AH, 'NEW LINE$'

.CODE
MAIN PROC
    
;INITIALISE DS
    MOV AX,@DATA
    MOV DS,AX   ;INITIALISE DS  
    
;DISPLAY MESSAGE
    LEA DX,MSG  ;GET MESSAGE
    MOV AH,9    ;DISPLAY STRING FUNCTION
    INT 21h     ;DISPLAY MESSAGE  
    MOV AH,4CH
   
    
    LEA DX,MSG2  ;GET MESSAGE
    MOV AH,9    ;DISPLAY STRING FUNCTION
    INT 21h     ;DISPLAY MESSAGE
    MOV AH,4CH  ;BUILT IN FUNCTION TO CLEAR MSG
    INT 21H 
     
;RETURN TO DOS 

    
    MAIN ENDP
END MAIN
    